# Machine Learning Algorithms Lab CIA 2

- Rohit Arrunachalam IOT B

Q1.Implement a neural network from scratch. Take any dataset. If you take a regression problem, use the equations derived in the class. If you take a classification problem, use the below equations: (run minimum 200 iterations and get the result). Use the gradient descent optimization technique for weight optimization.

In [10]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

d = pd.read_csv(r"C:\Users\Rohit\SNU\Sem 6\ML\cia2\dataset.csv")

In [11]:
d.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [12]:
d = np.array(d)
m,n = d.shape

In [14]:
dd = d.T
y = dd[0]
x = dd[1:n]
x = x / 255

In [16]:
def generate():
    w1 = 0.1*np.random.randn(100,783)
    b1 = 0.1*np.random.randn(100,1)
    w2 = 0.1*np.random.randn(10,100)
    b2 = 0.1*np.random.randn(10,1)
    return w1,b1,w2,b2

def sigmoid(z):
    return 1/(1+np.exp(-z))

def forward(w1,b1,w2,b2,x):
    z1 = w1.dot(x)+b1
    a1 = sigmoid(z1)
    z2 = w2.dot(a1)+b2
    a2 = sigmoid(z2)
    return z1,a1,z2,a2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def der(z):
    return sigmoid(z)*(1-sigmoid(z))
    
def back(z1,a1,z2,a2,w1,w2,x,y):
    one_y = one_hot(y)
    er = a2 - one_y
    delt = er * der(z2)
    dw2 = 1 / m *delt.dot(a1.T)
    db2 = 1 / m * np.sum(er)
    delt_hid = w2.T.dot(delt) * der(z1)
    dw1 = 1 / m * delt_hid.dot(x.T)
    db1 = 1 / m * np.sum(delt_hid)
    
    return dw1,db1,dw2,db2

def update(w1,b1,w2,b2,dw1,db1,dw2,db2,a):
    w1 = w1 - a*dw1
    b1 = b1 - a *db1
    w2 = w2 - a*dw2
    b2 = b2 - a *db2
    return w1,b1,w2,b2
    

In [17]:
def get_predictions(a2):
    return np.argmax(a2, 0)

def get_accuracy(predictions, y):
    print(predictions, y)
    return np.sum(predictions == y) / y.size

def gradient(x,y,a,it):
    w1,b1,w2,b2 = generate()
    for i in range(it):
        z1,a1,z2,a2 = forward(w1,b1,w2,b2,x)
        dw1,db1,dw2,db2 = back(z1,a1,z2,a2,w1,w2,x,y)
        w1,b1,w2,b2 = update(w1,b1,w2,b2,dw1,db1,dw2,db2,a)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(a2)
            print(get_accuracy(predictions, y))
    return w1, b1, w2, b2

In [18]:
w1, b1, w2, b2 = gradient(x, y, 0.10,200)

Iteration:  0
[8 0 8 ... 0 8 8] [0 0 0 ... 0 0 0]
0.13202380952380952
Iteration:  10
[8 0 8 ... 0 3 4] [0 0 0 ... 0 0 0]
0.15328571428571428
Iteration:  20
[8 0 9 ... 0 3 4] [0 0 0 ... 0 0 0]
0.14833333333333334
Iteration:  30
[8 7 9 ... 0 3 4] [0 0 0 ... 0 0 0]
0.145
Iteration:  40
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.1433809523809524
Iteration:  50
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.1423095238095238
Iteration:  60
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.14152380952380952
Iteration:  70
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.14114285714285715
Iteration:  80
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.14083333333333334
Iteration:  90
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.1405
Iteration:  100
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.14026190476190475
Iteration:  110
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.13995238095238094
Iteration:  120
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.13976190476190475
Iteration:  130
[8 7 9 ... 0 7 4] [0 0 0 ... 0 0 0]
0.1395952380952381
Iteration:  140
[8 7 9 ... 0 7 4]

Q2. For the same dataset, build a neural network using keras library. Run the same number of epochs and compare the results obtained with your model vs the built-in keras model.

In [19]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.utils import to_categorical

In [20]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape((x_train.shape[0], 28, 28, 1)).astype('float32') / 255
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1)).astype('float32') / 255

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

11490434/11490434 [==============================] - 5s 0us/step


In [21]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28, 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [23]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=200, batch_size=64, validation_split=0.2)

Epoch 1/200
750/750 [==============================] - 5s 5ms/step - loss: 0.0511 - accuracy: 0.9845 - val_loss: 0.0949 - val_accuracy: 0.9726
Epoch 2/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0402 - accuracy: 0.9883 - val_loss: 0.0903 - val_accuracy: 0.9734
Epoch 3/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0319 - accuracy: 0.9914 - val_loss: 0.0910 - val_accuracy: 0.9737
Epoch 4/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0259 - accuracy: 0.9927 - val_loss: 0.0901 - val_accuracy: 0.9763
Epoch 5/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0207 - accuracy: 0.9943 - val_loss: 0.0891 - val_accuracy: 0.9760
Epoch 6/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0161 - accuracy: 0.9960 - val_loss: 0.0894 - val_accuracy: 0.9767
Epoch 7/200
750/750 [==============================] - 4s 5ms/step - loss: 0.0148 - accuracy: 0.9961 - val_loss: 0.0890 - val_accuracy: 0.9762

In [24]:
_, accuracy = model.evaluate(x_test, y_test)
print('Accuracy on test set:', accuracy)

313/313 [==============================] - 1s 3ms/step - loss: 0.1987 - accuracy: 0.9818
Accuracy on test set: 0.9818000197410583


### Inference

We can clearly say that The Keras model achieved better accuracy on the same task than the gradient descent one built from  scratch due to lesser loss.